force-app/main/default/objects/Clinical_Study__c/Clinical_Study__c.object-meta.xml
<CustomObject>
    <label>Clinical Study</label>
    <nameField>
        <displayFormat>CS-{0000}</displayFormat>
        <label>Study Participant Key Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Studies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Participant__c/Study_Participant__c.object-meta.xml
<CustomObject>
    <label>Study Participant</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Study Participant Key Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Study Participant</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Participant__c/fields/Clinical_Study__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Study__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Study</label>
    <referenceTo>Clinical_Study__c</referenceTo>
    <relationshipLabel>Study Participant</relationshipLabel>
    <relationshipName>Study_Participant</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Study_Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Study Participant</relationshipLabel>
    <relationshipName>Study_Participant</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/batch-lesson/tests/classes/Test_TriggerStudyParticipant.cls
/**
* Created by user on 04.09.2019.
*/

@IsTest
private class Test_TriggerStudyParticipant {
    @TestSetup
    static void loadDate() {
        Contact contact = new Contact(LastName = 'Test');
        List<Clinical_Study__c> clinicalStudy = new List<Clinical_Study__c>([
                SELECT Id
                FROM Clinical_Study__c
                LIMIT 2]);
        Study_Participant__c studyParticipant = new Study_Participant__c(
                Contact__c = contact.Id,
                Clinical_Study__c = clinicalStudy[0].Id
        );
        insert contact;
        insert  clinicalStudy;
        insert studyParticipant;
    }

    @isTest
    static void testUpdateStudyParticipantKey() {
        Contact contact = [
                SELECT Id, Name
                FROM Contact
                WHERE LastName = 'Test'
        ];


    }
}