force-app/main/default/objects/Clinical_Study__c/Clinical_Study__c.object-meta.xml
<CustomObject>
    <label>Clinical Study</label>
    <nameField>
        <displayFormat>CS-{0000}</displayFormat>
        <label>Study Participant Key Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Studies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Participant__c/Study_Participant__c.object-meta.xml
<CustomObject>
    <label>Study Participant</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Study Participant Key Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Study Participant</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Participant__c/fields/Clinical_Study__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Study__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Study</label>
    <referenceTo>Clinical_Study__c</referenceTo>
    <relationshipLabel>Study Participant</relationshipLabel>
    <relationshipName>Study_Participant</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Study_Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Study Participant</relationshipLabel>
    <relationshipName>Study_Participant</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Study_Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>open</fullName>
                <default>true</default>
                <label>open</label>
            </value>
            <value>
                <fullName>closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/triggers-lesson/classes/StudyParticipantTriggerHandler.cls
/**
 * Created by user on 02.09.2019.
 */

public with sharing class StudyParticipantTriggerHandler {
        public static void updateStudyParticipantKey(List<Study_Participant__c> spList) {
            Set<Id> clinicalStudyIds = new Set<Id>();
            for(Study_Participant__c sp : spList) clinicalStudyIds.add(sp.Clinical_Study__c);

            List<Clinical_Study__c> clinicalStudies = [
                    SELECT Id, Name
                    FROM Clinical_Study__c
                    WHERE Id IN :clinicalStudyIds
            ];

            //var1
            Map<Id, Clinical_Study__c> clinicalStudyMap = new Map<Id, Clinical_Study__c>();
            for(Clinical_Study__c clinicalStudy : clinicalStudies) clinicalStudyMap.put(clinicalStudy.Id, clinicalStudy);

            //var2
            //clinicalStudyMap = new Map<Id, Clinical_Study__c>(clinicalStudies);

            for(Study_Participant__c sp : spList) {
                String studyName = clinicalStudyMap.get(sp.Clinical_Study__c).Name;
            sp.Study_Participant_Key__c = sp.Contact__c + ' ' + studyName;
            }
        }
    public static void updateCurrentStudyParticipant(List<Id> contactIds) {
        List<Study_Participant__c> studyParticipants = [
                SELECT Id, Name, Status__c
                FROM Study_Participant__c
                WHERE Id = :contactIds AND Status__c = 'Open'
        ];
        Map<Id, List<Id>> studyParticipantsByContactMap = new Map<Id, List<Id>>();

        for (Study_Participant__c studyParticipant : studyParticipants){
            List<Id> studyParticipantsForContacts = studyParticipantsByContactMap.get(studyParticipant.Contact__c);
            if (studyParticipantsForContacts == null) studyParticipantsForContacts = new List<Id>();
            studyParticipantsForContacts.add(studyParticipant.Id);
            studyParticipantsByContactMap.put(studyParticipant.Contact__c, studyParticipantsForContacts);
        }

        List<Contact> contacts = [SELECT Id, Current_Study__c FROM Contact WHERE Id IN: contactIds];

        for (Contact contact : contacts) {
            List<Id> studyParticipantsForContacts = studyParticipantsByContactMap.get(contact.Id);
            if (studyParticipantsForContacts == null) studyParticipantsForContacts = new List<Id>();
            if(contact.Current_Study__c == null || !studyParticipantsForContacts.contains(contact.Current_Study__c)) {
                if(studyParticipantsForContacts.size() > 0) {
                    contact.Current_Study__c = studyParticipantsForContacts.get(0);
                } else {
                    contact.Current_Study__c = null;
                }
            }
        }

        update contacts;

    }

    public static void updateStudyParticipant(Map<Id, Study_Participant__c> oldMap, List<Study_Participant__c> newList){
        List<Id> contactIds = new List<Id>();
        for(Study_Participant__c sp : newList) {
            if(oldMap == null || (oldMap.get(sp.Id).Status__c != sp.Status__c && sp.Status__c == 'Closed')) {
                contactIds.add(sp.Contact__c);
            }
        }

        updateCurrentStudyParticipant(contactIds);
    }
}