force-app/main/default/objects/Account/fields/Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Country__c</fullName>
    <label>Billing Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Billing_State__c.field-meta.xml
<CustomField>
    <fullName>Billing_State__c</fullName>
    <label>Billing State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/lightning-components-lesson/classes/AccountFilter.cls
/**
 * Created by Dasha Mitina on 09.09.2019.
 */

public with sharing class AccountFilter implements SearchFilter{

    public List<String> getFields() {
        return new List<String>{
                'Name',
                'Billing_Country__c',
                'Billing_City__c',
                'Billing_State__c',
                'Billing_Street__c'
        };
    }

    public SObjectType getSObjectType() {
        return Account.getSObjectType();
    }

    public String getFilterString() {
        return '';
    }

}